services:
  dreal:
    build:
      context: .
      dockerfile: ./dreal-container/dockerfile
    volumes:
      - ./:/workspace
    working_dir: /workspace
    # usage for scripts:
    # docker compose run --rm dreal file.py
    # for shell:
    # docker compose run --rm --entrypoint bash dreal
